"""Render a SlideDeck to a .pptx using python-pptx.

Pure renderer — no LLM, no network. Layout: a title slide, then one content
slide per finding (title + up to 3 bullets + a source-URL footer).
"""

from __future__ import annotations

import io
from pathlib import Path

from pptx import Presentation
from pptx.util import Pt

from polymath.models.schemas import SlideDeck

_MAX_BULLETS = 3
_TITLE_LAYOUT = 0  # "Title Slide"
_CONTENT_LAYOUT = 1  # "Title and Content"


def render_deck(deck: SlideDeck, path: str | Path) -> Path:
    """Render the deck to a .pptx file at `path` and return the path."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    _build_presentation(deck).save(str(path))
    return path


def deck_to_bytes(deck: SlideDeck) -> bytes:
    """Render the deck to in-memory .pptx bytes (for downloads)."""
    buf = io.BytesIO()
    _build_presentation(deck).save(buf)
    return buf.getvalue()


def _build_presentation(deck: SlideDeck) -> Presentation:
    prs = Presentation()

    # Title slide.
    title_slide = prs.slides.add_slide(prs.slide_layouts[_TITLE_LAYOUT])
    title_slide.shapes.title.text = deck.title
    if len(title_slide.placeholders) > 1:
        title_slide.placeholders[1].text = "Generated by Polymath"

    # One content slide per finding.
    for slide in deck.slides:
        s = prs.slides.add_slide(prs.slide_layouts[_CONTENT_LAYOUT])
        s.shapes.title.text = slide.title

        body = s.placeholders[1].text_frame
        body.clear()
        bullets = slide.bullets[:_MAX_BULLETS] or [""]
        for i, bullet in enumerate(bullets):
            para = body.paragraphs[0] if i == 0 else body.add_paragraph()
            para.text = bullet
            para.level = 0

        if slide.source_url:
            _add_source_footer(s, slide.source_url)

    return prs


def _add_source_footer(slide, source_url: str) -> None:
    """Add a small source-URL textbox along the bottom of the slide."""
    from pptx.util import Emu

    width = slide.part.package.presentation_part.presentation.slide_width
    height = slide.part.package.presentation_part.presentation.slide_height
    box = slide.shapes.add_textbox(
        left=Emu(int(width * 0.05)),
        top=Emu(int(height * 0.92)),
        width=Emu(int(width * 0.9)),
        height=Emu(int(height * 0.06)),
    )
    tf = box.text_frame
    tf.text = f"Source: {source_url}"
    tf.paragraphs[0].runs[0].font.size = Pt(10)
